version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:12.13.1-browsers
        steps:
            - checkout
            - run: yarn
    test:
        docker:
            - image: circleci/node:12.13.1-browsers
        steps:
            - checkout
            - run: yarn run lint

workflows:
    build_and_test:
        jobs:
            - build
            - test

