version: 2.1
jobs:
    test:
        docker:
            - image: circleci/node:12.13.1-browsers
        steps:
            - checkout
            - run: yarn
            - run: yarn run lint
    deploy:
        docker:
            - image: circleci/node:12.13.1-browsers
        steps:
            - checkout
            - run: yarn
            - run: npx semantic-release


workflows:
    test_and_deploy:
        jobs:
            - test
            - deploy:
                requires:
                    - test
                filters:
                    branches:
                        only: master
